builders:
  # name of the builder
  vocab_class:
    # library URI containing the builder - maps to `lib/member_count_library_generator.dart`
    import: "package:rdf_vocab_gen/builder.dart"
    # Name of the function in the above library to call.
    builder_factories: ["vocabLibraryBuilder"]
    build_extensions: { ".dart": ["vocab.g.part"] }
    # Will automatically run on any package that depends on it
    auto_apply: dependents
    # Generate the oLibraryBuilderutput directly into the package, not to a hidden cache dir
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
